### ISSUE TITLE
Name of IP

### ISSUE THREAD

**Issue by kunalg123** [ankursah5/avsd_bgr#1]
Hi Ankur,
The name of your IP doesn't seem to tell what IP it is. Can you please change it to some standard name?
You might want to refer to some industry grade Bandgap Datasheet

**Comment by ankursah5** [comment]
Hi Kunal,
can you review the changed name? If this sounds okay, you might want to close the issue.

**Comment by kunalg123** [comment]
Thanks Ankur
This looks good.
Closing the issue now
