### ISSUE TITLE
README corrections

### ISSUE THREAD

**Issue by kunalg123** [ankursah5/avsd_bgr#2]
Hi Ankur
The name of the IP in title and README don't match. You might want to change names of IP used in README

**Comment by ankursah5** [comment]
Hi Kunal,

As per specifications, i have changed the name of IP in README. 

Can you review it? If it is okay, you might close this issue.

**Comment by kunalg123** [comment]
The below line still needs to be changed

 git clone https://github.com/ankursah5/avsd_bgr

**Comment by ankursah5** [comment]
Hello Kunal,

Sorry for the incomplete changes. 
I have changed the mentioned line and other messaging related to it.

Please review it and if everything is okay you might close the issue.

**Comment by kunalg123** [comment]
Looks good
