### ISSUE TITLE
Typical Performance characteristics

### ISSUE THREAD

**Issue by kunalg123** [ankursah5/avsd_bgr#3]
Hi Ankur
Under Typical performance characteristics, use spec sheet which was shared during internship program

Thanks

**Comment by ankursah5** [comment]
Hello Kunal,

Sorry for the inconvenience.
I have updated the sheet as per specification i received and posted it under parameters section. 
The values still some reviews as there were some changes during internship program. I will keep it updated. 

If it looks okay, you might close the issue.

**Comment by kunalg123** [comment]
We will get it reviewed internally at VSD. Closing the issue for now
